### ISSUE TITLE
css file with wrong path and dropdown is actually drop up

### ISSUE THREAD

**Issue by joelpro2** [long-woo/vue-bootstrap-selectpicker#1]
Hi,
First i wanna say you've made a good work.
I've found some minor mistakes such as:
The import of vue-bootstrap-selectpicker.min.css has a wrong path (you missed "dist"), so it should be like `import 'vue-bootstrap-selectpicker/`**dist/**`css/vue-bootstrap-selectpicker.min.css'` and the same with the js file.

Another detail is that your data attribute upShow is set to default true and there is no prop to change it.
It should be set default to false and should have a prop to change it.
![vue-selectpicker](https://user-images.githubusercontent.com/11671788/48477698-2ac20a00-e7fa-11e8-9513-20645c9b1300.png)

You should permit to disable the styling for custom design like a prop `default-class=""` which removes bootstrap classes

**Comment by long-woo** [comment]
@joelpro2 Thank you very much for finding these errors for me.

The `upShow` data property is calculated after the component is `mounted`. This design may be a bit unreasonable.

I will solve these problems as soon as possible.

**Comment by joelpro2** [comment]
eventually for some reason it's dropping down now

**Comment by long-woo** [comment]
Update  v1.0.4
Add a `placement` attribute to set the `top` or `bottom` value
``` html
<select-picker  placement="top"...
```
