### ISSUE TITLE
Dropdown throws errors if a list with search is type numeric

### ISSUE THREAD

**Issue by joelpro2** [long-woo/vue-bootstrap-selectpicker#2]
If the dropdown is numeric and searchable, it will throw an error when you search by a number because you're lower-casing the value and a number cannot be lower-cased
![vue-selectpicker](https://user-images.githubusercontent.com/11671788/48480526-a1fb9c00-e802-11e8-9806-fafba8315b45.png)

**Comment by long-woo** [comment]
Update v1.0.4
