### ISSUE TITLE
:size not working

### ISSUE THREAD

**Issue by Scronheim** [long-woo/vue-bootstrap-selectpicker#7]
`<select-picker placement="bottom" id="complexes" :dropdown-data="complexes" :size="3" v-model="selectedComplex" @change="changeSelect" search/>`
with this configuration :size not working
P.S. complexes array contains over 800 elements
Package version: "vue-bootstrap-selectpicker": "^1.0.6"

**Comment by long-woo** [comment]
Hello, can you provide the demo address?

**Comment by Scronheim** [comment]
Hi, unfortunately this is not possible at the moment

data for reproduce:
```
complexes: [
0:"000-17",
1:"01-14",
2:"01-16",
3:"01-17",
4:"01/08",
5:"02-16"
]
```
Search works correctly, but size does not limit select's dropdown menu
[screenshot](https://i.imgur.com/ExrdLGC.png)
as you can see the scroll on the right side is very long

**Comment by Scronheim** [comment]
it seems that the component is waiting for the object to be necessarily with the text and value attributes
